### ISSUE TITLE
Error on attribute value/substring matching selectors

### ISSUE THREAD

**Issue by bartveneman** [mdevils/node-css-selector-parser#20]
### 📦 Versions
css-selector-parser: **1.3.0**
Node: **10.15.2**

### 😇 Expected behaviour
Parser parses `[attr^=value]` without throwing error

### 🐛 Actual behaviour
Parser throws `Unexpected " "`

### 📚 Related resources
- Reduced testcase: https://repl.it/@bartveneman/css-selector-parser-reduced-test-case
- W3C Attribute Selectors Level 3: https://www.w3.org/TR/2018/CR-selectors-3-20180130/#attribute-selectors

I found it throws an error for all attribute selectors, except the attribute presence selector:
```js
'[prop]' // works
'[prop^=val]' // Error
'[prop|=val]' // Error
'[prop~=val]' // Error
'[prop*=val]' // Error
'[prop$=val]' // Error
```

**Comment by bartveneman** [comment]
My bad, I totally missed this part in the readme:

```js
parser.registerNestingOperators('>', '+', '~');
parser.registerAttrEqualityMods('^', '$', '*', '~');
```

**Comment by mdevils** [comment]
@bartveneman no worries
