### ISSUE TITLE
Complications

### ISSUE THREAD

**Issue by TrySound** [mdevils/node-css-selector-parser#5]
Why not just `require('css-selector-parser')` without `.CssSelectorParser` ?

**Comment by TrySound** [comment]
And what means the second and the third arguments in `parse` method

**Comment by mdevils** [comment]
Hello!

> Why not just require('css-selector-parser') without .CssSelectorParser ?

For the ability to extend API later.

> And what means the second and the third arguments in parse method.

There are no second and third arguments.

**Comment by TrySound** [comment]
Sorry, it was inspect's

**Comment by TrySound** [comment]
How about build method?

**Comment by mdevils** [comment]
> What about build method?

What do you mean?

**Comment by TrySound** [comment]
I need to build result of parse with some changes to string.
Output could be an array of selectors.

**Comment by mdevils** [comment]
Oh, I see. You can use method `render`.

Example:
```
parser.render(parser.parse('.cls'));
```

Better documentation is coming soon.

**Comment by TrySound** [comment]
Thanks! Waiting for it.
