### ISSUE TITLE
eachRule method

### ISSUE THREAD

**Issue by TrySound** [mdevils/node-css-selector-parser#8]
Something like this.
```js
selector = parser(selector).eachRule(function (rule) {
	if(rule.tagName === 'icn') {
		return '.icn'; // will be parsed and added to tree
	}
}).render();
```

**Comment by TrySound** [comment]
Also you may look at [postcss API](https://github.com/postcss/postcss/blob/master/API.md)

**Comment by TrySound** [comment]
[My realization](https://gist.github.com/TrySound/b21efe262f4dc64c15d3)

**Comment by TrySound** [comment]
And maybe some wrapper method like `.eachClassName` and `.eachTagName`

**Comment by TrySound** [comment]
Hm.. no, just eachClass, callback of which return new className. not selector. Like this
```js
Parser.prototype.eachClassName = function (cb) {
	this.eachRule(function (rule) {
		if(rule.classNames) {
			rule.classNames = rule.classNames.map(cb);
		}
	});

	return this;
};
```

**Comment by TrySound** [comment]
And `.eachSelector` for semantics will be good:)

**Comment by mdevils** [comment]
Sorry, I'm not sure about this feature.

**Comment by TrySound** [comment]
There is [postcss-selector-parser](https://github.com/postcss/postcss-selector-parser) which has this feature.

**Comment by mdevils** [comment]
I mostly not sure about the implementation. The result of the parser is an array right now and I would not like to add extra types there. I think this should be done differently introducing a method to Parser class:
```js
import {CssSelectorParser} from 'css-selector-parser';

var parser = new CssSelectorParser();
parser.registerSelectorPseudos('has');
parser.registerNestingOperators('>', '+', '~');
parser.registerAttrEqualityMods('^', '$', '*', '~');
parser.enableSubstitutes();

var parsedSelector = parser.parse('.class1 > div .class2');
var resultSelector = parser.mapClassNames(parsedSelector, function(className) {
    return 'prefix-' + className;
});
```

What do you think?

**Comment by TrySound** [comment]
LGTM
Different APIs let choose.

**Comment by mdevils** [comment]
Would you like to implement this and send a PR?

**Comment by TrySound** [comment]
@mdevils Sorry, I already choose postcss-selector-parser
